# Generated by Django 2.1.1 on 2018-09-12 00:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ingresar el Título de la Revista', max_length=100)),
                ('numero', models.IntegerField(help_text='Ingresar el Número de la Revista')),
                ('pagina', models.IntegerField(help_text='Ingresar la página del Artículo')),
                ('resumen', models.TextField(help_text='Ingresar Resumen del artículo')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del Autor', max_length=100)),
                ('apellido', models.CharField(help_text='Apellido del Autor', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InstanciaRevista',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID unica para cada ejemplar', primary_key=True, serialize=False)),
                ('fechaDevolucion', models.DateField(blank=True, null=True)),
                ('estado', models.IntegerField(blank=True, choices=[('1', 'Disponible'), ('2', 'Reservado'), ('3', 'En Préstamo')], default=1, help_text='Estado de Prestamo de la Revista', max_length=1)),
            ],
            options={
                'ordering': ['fechaDevolucion'],
            },
        ),
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], help_text='Ingresar mes de la Revista')),
                ('anio', models.IntegerField(help_text='Ingresar Año de la Revista')),
            ],
        ),
        migrations.AddField(
            model_name='instanciarevista',
            name='Revista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.Revista'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='autores',
            field=models.ManyToManyField(to='biblioteca.Autor'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='revista',
            field=models.ForeignKey(help_text='Revista en la que está el artículo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.Revista'),
        ),
    ]
