# Generated by Django 2.1.1 on 2018-09-12 00:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID unica para cada ejemplar', primary_key=True, serialize=False)),
                ('fechaDevolucion', models.DateField(blank=True, null=True, verbose_name='Fecha de Devolución')),
                ('estado', models.IntegerField(blank=True, choices=[('1', 'Disponible'), ('2', 'Reservado'), ('3', 'En Préstamo')], default=1, help_text='Estado de Prestamo de la Revista', max_length=1)),
                ('Revista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.Revista')),
            ],
            options={
                'verbose_name_plural': 'Ejemplares',
                'ordering': ['fechaDevolucion'],
            },
        ),
        migrations.RemoveField(
            model_name='instanciarevista',
            name='Revista',
        ),
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterField(
            model_name='articulo',
            name='numero',
            field=models.IntegerField(help_text='Número de Artículo en la Revista'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='pagina',
            field=models.IntegerField(help_text='Página del Artículo'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='resumen',
            field=models.TextField(help_text='Resumen del Artículo'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='titulo',
            field=models.CharField(help_text='Título del Artículo', max_length=100),
        ),
        migrations.DeleteModel(
            name='InstanciaRevista',
        ),
    ]
