# Generated by Django 2.1.1 on 2018-09-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_auto_20180912_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejemplar',
            name='estado',
            field=models.IntegerField(blank=True, choices=[('1', 'Disponible'), ('2', 'Reservado'), ('3', 'En Préstamo')], default=1, help_text='Estado de Prestamo de la Revista'),
        ),
    ]
