# Generated by Django 2.1.1 on 2018-09-12 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_auto_20180912_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejemplar',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
