# Generated by Django 2.1.1 on 2018-09-12 23:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_auto_20180912_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejemplar',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cad23528-17ee-4151-9a33-b6dacdeb21b1'), help_text='Identificación única del Ejemplar', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='revista',
            name='anio',
            field=models.IntegerField(max_length=4),
        ),
    ]
