# Generated by Django 2.1.1 on 2018-09-13 18:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_auto_20180912_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(blank=True, help_text='Nombre del Autor', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ejemplar',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d87848fd-521f-4c9e-9248-c60bd7a48dea'), help_text='Identificación única del Ejemplar', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='revista',
            name='anio',
            field=models.IntegerField(),
        ),
    ]
