# Generated by Django 2.1.1 on 2018-09-13 19:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0008_auto_20180913_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejemplar',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b8e7fdd0-489f-4950-9519-65d6872f1445'), help_text='Identificación única del Ejemplar', primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
