# Generated by Django 2.1.1 on 2018-09-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0009_auto_20180913_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejemplar',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
