# Generated by Django 2.1.1 on 2018-09-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0011_auto_20180913_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejemplar',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Reservado', 'Reservado'), ('En Prestamo', 'En Préstamo')], default='Disponible', help_text='Estado de Prestamo de la Revista', max_length=15),
        ),
    ]
