# Generated by Django 2.1.1 on 2018-09-13 22:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0012_auto_20180913_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejemplar',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='ID Unica para este ejemplar', primary_key=True, serialize=False),
        ),
    ]
